default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: detect-private-key

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: python
        types: [python]
        require_serial: true
        args: ["-rn", "-sn"]  # Only display messages, don't display the score

      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: python
        types: [python]

      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: python
        types: [python]

      - id: isort
        name: isort
        entry: poetry run isort
        language: python
        types: [python]

      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: python
        types: [python]
        pass_filenames: false
        always_run: true  # Ensure it runs regardless of changes

      - id: unittest
        name: unittest
        entry: poetry run python -m unittest discover -p '*_unittest.py'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true  # Ensure it runs regardless of changes
